"""Render result JSON files into a publishable Markdown table."""

from __future__ import annotations

import json
from pathlib import Path


def _fmt(x, suffix: str = "") -> str:
    if x is None:
        return "—"
    if isinstance(x, float):
        return f"{x:g}{suffix}"
    return f"{x}{suffix}"


def load_results(results_dir: Path) -> list[dict]:
    out = []
    for p in sorted(results_dir.glob("run-*.json")):
        try:
            data = json.loads(p.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        out.extend(data.get("results", []))
    return out


def load_fingerprints(results_dir: Path) -> dict[str, dict]:
    fps = {}
    for p in results_dir.glob("fingerprint-*.json"):
        try:
            data = json.loads(p.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        fps[data.get("fingerprint_id", "")] = data
    return fps


def render(results_dir: Path) -> str:
    results = load_results(results_dir)
    fps = load_fingerprints(results_dir)
    if not results:
        return "# StrixBench results\n\n_No results yet. Run `strixbench run` first._\n"

    # Sort by decode throughput, fastest first.
    results.sort(key=lambda r: (r.get("decode_tps") or 0), reverse=True)

    lines = ["# StrixBench results", ""]

    if fps:
        lines += ["## Stacks", ""]
        for fid, fp in fps.items():
            lines.append(
                f"- **`{fid}`** — {fp.get('gpu_name') or '?'} ({fp.get('gfx_target','?')}), "
                f"kernel {fp.get('kernel','?')}, ROCm {fp.get('rocm_version') or '—'}, "
                f"{fp.get('mesa_radv_version') or 'RADV ?'}, "
                f"{_fmt(fp.get('unified_total_gb'),' GB')} unified "
                f"({_fmt(fp.get('gpu_addressable_gb'),' GB')} GPU-addressable)"
            )
        lines.append("")

    lines += ["## Throughput & efficiency", ""]
    header = [
        "Model", "Quant", "Size", "Backend",
        "Prefill tok/s", "Decode tok/s", "GPU W", "Pkg W", "tok/J", "Stack",
    ]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")
    for r in results:
        decode = _fmt(r.get("decode_tps"))
        if r.get("decode_tps_stddev"):
            decode += f" ±{_fmt(r['decode_tps_stddev'])}"
        row = [
            r.get("model_name", "?"),
            r.get("model_quant") or "—",
            _fmt(r.get("model_size_gb"), " GB"),
            r.get("engine_backend", "?"),
            _fmt(r.get("prefill_tps")),
            decode,
            _fmt(r.get("gpu_avg_w")),
            _fmt(r.get("pkg_avg_w")),
            _fmt(r.get("decode_tokens_per_joule")),
            f"`{r.get('fingerprint_id','')}`",
        ]
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "_Generated by StrixBench. Decode is memory-bandwidth bound on "
              "Strix Halo — MoE models win big here._", ""]
    return "\n".join(lines)
